compio-rs/compio

- Cargo.toml
- examples/tick.rs
- src/driver/iour/mod.rs
- src/driver/mod.rs
- src/task/runtime.rs
- src/task/time.rs
Fixes #11 
This is the easiest solution AFAIK. Maintain unbounded queues myself, and submit them in a loop. `SegQueue` is used because the linux signal may interrupt the thread and cause sync problems.
@redbaron Do you like this solution?
> Maintain squeue & cqueue manually in io-uring.

- README.md
- examples/driver.rs
- src/driver/iocp/mod.rs
- src/driver/iour/mod.rs
- src/driver/mod.rs
- src/event/iocp.rs
- src/task/runtime.rs
- tests/driver.rs
https://github.com/Berrysoft/compio/pull/29#pullrequestreview-1618686146
/cc @DXist
> Move `RefCell` to runtime

- src/attacher.rs
- src/driver/iocp/mod.rs
- src/driver/mod.rs
- src/fs/file.rs
- src/lib.rs
- src/named_pipe.rs
- src/net/socket.rs
- src/net/tcp.rs
- src/net/udp.rs
- src/net/unix.rs
- tests/runtime.rs
Fixes #39 
This PR allows you to:
* Accept a stream from a listener, and move the stream *immediately* to another thread.
* Only attach the handle to the thread-local runtime at first call to an async method.
* Use IOCP without undocumented APIs.
And it disallows you to:
* Attach a handle to the driver multiple times.
* Attach a handle to multiple drivers.
* Move an attached handle to another thread.
Note about try_clone: it *doesn't* clear attach state.
> Lazy attach

- src/net/socket.rs
- tests/tcp_connect.rs
I've found the following patch - https://lore.kernel.org/all/a545c1ae-02a7-e7f1-5199-5cd67a52bb1e@kernel.dk/T/#mc720f37164873a8853bb1953515329c242a89a3b
Using blocking socket allows tests to pass on Linux 5.15.
> Fix eagain on linux

- src/event/iocp.rs
- src/event/iour.rs
- src/event/mio.rs
- src/signal/unix.rs
- src/signal/windows.rs
- tests/event.rs
Users may forget the signal future, making the event handle dangling.
> Make `EventHandle` owns the fd.

- Cargo.toml
- README.md
- examples/driver.rs
- src/driver/iocp/mod.rs
- src/driver/iocp/op.rs
- src/driver/iour/mod.rs
- src/driver/mio/mod.rs
- src/driver/mod.rs
- src/event/iocp.rs
- src/fs/file.rs
- src/key.rs
- src/lib.rs
- src/named_pipe.rs
- src/op.rs
- src/task/op.rs
- src/task/runtime.rs
- tests/driver.rs
- tests/event.rs
Introduced a new safe wrapper called `PollDriver`.
Maybe need to name it `Driver`, and change the original `Driver` type to `NativeDriver`.
> Make driver safe

- Cargo.toml
- README.md
- src/driver/mod.rs
- src/driver/poll/mod.rs
- src/driver/poll/op.rs
- src/driver/unix/mod.rs
- src/event/pipe.rs
- src/lib.rs
- src/op.rs
- tests/driver.rs
@George-Miao you've always want this:)
However I've found some problems:
* The `key` of `Event` is said to identify the fd, I don't know whether an fd could be registered with multiple different keys.
* Don't know if it is allowed to add one fd several times with different keys.
Bonus: Closes #67
> Try to use polling instead of mio.

- Cargo.toml
- azure-pipelines.yml
- src/driver/mod.rs
- src/net/socket.rs
Linux system which doesn't enable io-uring can use epoll instead. However, epoll doesn't support disk files, which means the file IO is synconized.
> Make polling available on Linux.

- compio/src/attacher.rs
- compio/src/driver/mod.rs
- compio/src/driver/poll/mod.rs
- compio/src/driver/poll/op.rs
- compio/src/event/eventfd.rs
- compio/src/event/pipe.rs
- compio/src/fs/file.rs
- compio/src/net/socket.rs
Also unify the behavior of the `try_clone` method.
> Get use of `attach` for polling driver.

- compio-driver/Cargo.toml
- compio-driver/src/iocp/mod.rs
- compio-driver/src/iour/mod.rs
- compio-driver/src/lib.rs
- compio-driver/src/poll/mod.rs
- compio-runtime/src/event/iocp.rs
- compio-runtime/src/runtime/mod.rs
- compio/examples/driver.rs
- compio/tests/driver.rs
`Runtime::submit` is called after first `Future::poll`, so it's OK to return ready on push.
> Allow returning ready on push

- compio-driver/Cargo.toml
- compio-driver/src/iocp/mod.rs
- compio-driver/src/iocp/op.rs
- compio/tests/file.rs
- compio/tests/runtime.rs
Some IO methods may success immediately. However, it will also issue a packet to IOCP. Now in #82 we've allowed success immediately in `push`, so it is possible to handle these methods, and disable the packet issue.
We can disable the inner event handle of file object as well. It may improve the performance a little.
https://learn.microsoft.com/en-US/troubleshoot/windows/win32/asynchronous-disk-io-synchronous
https://devblogs.microsoft.com/oldnewthing/20190719-00/?p=102722
https://devblogs.microsoft.com/oldnewthing/20200221-00/?p=103466
https://github.com/dotnet/corefx/pull/15141
> Use SetFileCompletionNotificationModes when attaching.

- compio-driver/src/iocp/mod.rs
- compio-driver/src/iour/mod.rs
- compio-driver/src/lib.rs
- compio-driver/src/poll/mod.rs
- compio-driver/src/unix/mod.rs
- compio-runtime/src/runtime/mod.rs
- compio-runtime/src/runtime/op.rs
There could be such case:
```
Proactor::push      0
Proactor::poll      0
Proactor::pop       0
Proactor::push      0 // Because the previous op is popped.
Proactor::poll      0
Proactor::pop       0
Runtime::poll_task  0 // Boom because the second op replaces the first op.
```
This PR fixes this problem, making `poll_task` call `pop`. Therefore the behavior will be:
```
Proactor::push      0
Proactor::poll      0
Proactor::push      1 // Because the previous op is *not* popped.
Proactor::poll      1
Runtime::poll_task  0
Proactor::pop       0
```
This PR also makes `RawOp` totally hidden because the runtime doesn't need to know it.
> Pop the op later.

- compio-driver/src/lib.rs
- compio-driver/src/poll/mod.rs
If a resource is closed and a new resource reuses the closed fd, the resource chooses to attach itself, but it has already been registered to the poller. This may not be a problem on mac, but at least the implementation of darling reports an error.
> Check and renew fd in polling driver

- compio-macros/src/lib.rs
`proc_macro_crate::crate_name` takes crate name specified in `Cargo.toml`, which is `compio-runtime` in this case.
> Fix: unable to resolve `compio-runtime` in macros

- compio-buf/Cargo.toml
- compio-buf/src/io_buf.rs
- compio-buf/src/io_slice.rs
- compio-buf/src/lib.rs
- compio-driver/src/iour/op.rs
- compio-driver/src/poll/op.rs
- compio-driver/src/unix/op.rs
This PR adds `IoSlice` and `IoSliceMut` to `compio-buf` to provide a more flexible api compare to the std one.
> Add custom `IoSlice`

- compio/Cargo.toml
- compio/tests/dispatcher.rs
- compio/tests/event.rs
- compio/tests/file.rs
- compio/tests/runtime.rs
- compio/tests/tcp_accept.rs
- compio/tests/tcp_connect.rs
- compio/tests/udp.rs
- compio/tests/unix_stream.rs
This PR change `compio::test` in tests to `compio_macros::test`, and make it a mandatory dev dependency. `macros` feature of `compio` is optional, meaning tests have to be runned with feature flag. This also makes RA happy (instead of yelling macro not exist).
> Use `compio-macros` in tests

- .gitignore
- compio-net/src/tcp.rs
- compio-net/src/udp.rs
- compio/tests/runtime.rs
- compio/tests/tcp_connect.rs
`SockAddr` can be a tcp/udp socket addr, unix domain socket addr or others
but when using tcp/udp, the `SockAddr` is always ip+port, if users want to get the ip or port, or pass the addr to other other place which need a `SocketAddr`, user need to convert it to `SocketAddr` manually, so change tcp/udp addr type to `SocketAddr`
> refactor: change SockAddr return type to SocketAddr

- compio-driver/src/iour/op.rs
- compio-driver/src/lib.rs
- compio-driver/src/op.rs
- compio-driver/src/poll/mod.rs
- compio-driver/src/poll/op.rs
- compio-driver/src/unix/op.rs
- compio-fs/src/file.rs
- compio-fs/src/pipe.rs
- compio-io/src/read/ext.rs
- compio-io/src/read/mod.rs
- compio-io/src/write/ext.rs
- compio-io/src/write/mod.rs
- compio-net/src/socket.rs
- compio-net/src/tcp.rs
- compio-net/src/unix.rs
- compio-runtime/src/event/eventfd.rs
- compio-runtime/src/event/pipe.rs
- compio/tests/io.rs
- compio/tests/udp.rs
And add default impl for *_vectored_at.
Closes #92
> Add preadv & pwritev support

- compio-driver/Cargo.toml
- compio-driver/src/fusion/mod.rs
- compio-driver/src/fusion/op.rs
- compio-driver/src/iour/op.rs
- compio-driver/src/lib.rs
- compio-driver/src/op.rs
- compio-driver/src/poll/op.rs
- compio-driver/src/unix/op.rs
This PR added fusion driver, which will be enabled when both `io-uring` and `polling` are enabled, and will determine which to use during runtime. 
However, this does bring some overhead throughout the lifetime of the driver:
- The driver is an enum internally, meaning more branching
- Several OpCodes are now enum too due to divergence between `io-uring` and `polling` implementations.
- A one-time detection will be made when the first fusion driver is instantiated
@nazar-pc what do you think?
Closes #105
> feat(driver): fusion driver

- compio-buf/src/io_buf.rs
- compio-buf/src/iter.rs
- compio-buf/src/slice.rs
- compio-driver/src/iocp/op.rs
- compio-driver/src/iour/op.rs
- compio-driver/src/poll/op.rs
- compio-io/src/buffer.rs
- compio-io/src/read/ext.rs
- compio-io/src/read/mod.rs
- compio-io/src/util/internal.rs
- compio-io/src/util/repeat.rs
- compio/tests/io.rs
- compio/tests/runtime.rs
According to complains, we need to redesign IoBufMut and read series methods. Now these methods read data into both init and uninit region of the buffer.
Closes #113 
Closes #107 
/cc @George-Miao @nazar-pc
> feat(buf): redesign IoBufMut

- compio-fs/src/file.rs
- compio-fs/src/named_pipe.rs
- compio-fs/src/pipe.rs
- compio-net/src/lib.rs
- compio-net/src/resolve/mod.rs
- compio-net/src/socket.rs
- compio-net/src/tcp.rs
- compio-net/src/udp.rs
- compio-net/src/unix.rs
- compio/benches/net.rs
- compio/tests/udp.rs
Add impl `AsyncRead`, `AsyncWrite`, `AsyncWriteAt` for &T. Don't need for `AsyncReadAt` because it already accepts `&self`.
This PR enables users to start IO tasks in parallel.
> feat(fs, net): add impl for &T

- README.md
This PR adds a more obvious entry point for people who wish to contribute.
> doc: add contribution section to README.md

- compio-fs/src/named_pipe.rs
- compio-fs/src/open_options/mod.rs
- compio-fs/src/open_options/unix.rs
- compio-fs/src/open_options/windows.rs
- compio/benches/named_pipe.rs
- compio/examples/named_pipe.rs
A named pipe client can connect to a remote named pipe, so we should make the `open` method async.
> feat: async open named pipe client

- compio-driver/src/fusion/mod.rs
- compio-fs/src/pipe.rs
We need to re-export the specific opcode trait to allow users author their own ones.
> docs: fix warnings

- compio-runtime/src/lib.rs
This PR exposes `async_task::Task` from runtime crate, so that users can write out the return type of `spawn`
> refactor(runtime): expose `async_task::Task`

- compio-net/src/resolve/windows.rs
- compio-runtime/src/event/eventfd.rs
- compio-runtime/src/event/iocp.rs
- compio-runtime/src/event/pipe.rs
- compio-signal/src/unix.rs
- compio-signal/src/windows.rs
We should ensure that `Event` is oneshot. `wait` and `notify` should be called only once.
> refactor: ensure Event being oneshot

- Cargo.toml
- compio-http/src/backend.rs
- compio-tls/Cargo.toml
- compio-tls/tests/connect.rs
We can use the `read_buf` nightly feature with this new release.
> feat: update rustls to 0.22.0-alpha.4

- compio-buf/Cargo.toml
- compio-driver/Cargo.toml
- compio-fs/Cargo.toml
- compio-http-client/Cargo.toml
- compio-http/Cargo.toml
- compio-net/Cargo.toml
- compio-runtime/Cargo.toml
- compio-signal/Cargo.toml
- compio-tls/Cargo.toml
- compio/Cargo.toml
Nearly all docs build failed:(
The arg `--cfg docsrs` was treated as one argument.
> docs: fix rustdoc args

- compio-driver/Cargo.toml
- compio-driver/src/fusion/mod.rs
- compio-driver/src/iocp/mod.rs
- compio-driver/src/iour/mod.rs
- compio-driver/src/lib.rs
- compio-driver/src/poll/mod.rs
- compio-driver/tests/file.rs
- compio-runtime/Cargo.toml
- compio-runtime/src/event/iocp.rs
- compio-runtime/src/runtime/mod.rs
- compio/Cargo.toml
- compio/tests/runtime.rs
Closes #144
See also: #108
The waker of compio could be waked in other threads. They will push the task into the queue safely and wake up the proactor.
> feat(driver,runtime): wake up proactor from other threads

- compio-tls/Cargo.toml
This PR temporarilly pin-point the version of rustls, which is alpha and is subject to breaking change at any time. Follow up adaptation PR is required.
> fix(tls): fix rustls version

- compio-driver/src/fusion/mod.rs
- compio-fs/Cargo.toml
- compio-fs/src/file.rs
- compio-fs/src/lib.rs
- compio-fs/src/named_pipe.rs
- compio-fs/src/pipe.rs
- compio-io/src/lib.rs
- compio-net/Cargo.toml
- compio-net/src/lib.rs
- compio-net/src/socket.rs
- compio-net/src/tcp.rs
- compio-net/src/udp.rs
- compio-net/src/unix.rs
- compio-runtime/Cargo.toml
- compio-runtime/src/attacher.rs
- compio-runtime/src/event/eventfd.rs
- compio-runtime/src/event/pipe.rs
- compio-signal/src/unix.rs
- compio/Cargo.toml
- compio/examples/driver.rs
- compio/src/lib.rs
This is an experimental PR. It tries to force the user of `Attacher` to attach the source before using it. As a side-effect, `compio-fs` and `compio-net` must depend on `compio-runtime`.
> refactor(runtime): make Attacher a container

- compio-net/src/resolve/glibc.rs
- compio-net/src/resolve/mod.rs
- compio-net/src/resolve/windows.rs
The `AsyncResolver` need to cancel the async task on drop, in case the user drops it before the task completes.
> fix(net): cancel async resolver on drop

- compio-tls/Cargo.toml
- compio-tls/src/lib.rs
Closes #165 
Also updates rustls to remove the version pinning of rustls-pki-types
> fix(tls): report error if no tls backend enabled

- compio-driver/src/poll/mod.rs
- compio-driver/src/poll/op.rs
We can merge this method with `pre_submit`.
> refactor(driver,polling): remove `is_blocking`

- compio-driver/Cargo.toml
- compio-driver/src/fusion/mod.rs
- compio-driver/src/fusion/op.rs
- compio-driver/src/iocp/op.rs
- compio-driver/src/iour/mod.rs
- compio-driver/src/iour/op.rs
- compio-driver/src/op.rs
- compio-driver/src/poll/op.rs
- compio-driver/tests/file.rs
- compio-runtime/src/lib.rs
- compio-runtime/src/runtime/mod.rs
- compio-runtime/tests/event.rs
This is a requisite to fix #161 
An operation `Asyncify` is added to spawn a blocking method to a new thread.
In this PR, the thread poll is also added into io-uring driver. In the future, we may implement `CreateSocket` operation with that pool in case some old kernel doesn't support `socket` io-uring operation.
> feat(driver,runtime): add Asyncify op and `spawn_blocking`

- compio-driver/tests/file.rs
- compio/examples/driver.rs
`Proactor::poll` doesn't ensure that `entries` will be filled with at least one entry. It may be still empty.
> fix(test): push_and_wait should poll in a loop

- compio-driver/src/fusion/mod.rs
- compio-driver/src/iocp/mod.rs
- compio-driver/src/iour/mod.rs
- compio-driver/src/lib.rs
- compio-driver/src/poll/mod.rs
- compio-driver/src/unix/mod.rs
- compio-runtime/src/runtime/mod.rs
- compio-runtime/src/runtime/op.rs
Closes #164 
This PR records a flag in `RawOp`. It is set when polling the proactor.
> feat(driver): drop completed `RawOp` on `Proactor` dropping

- compio-signal/Cargo.toml
- compio-signal/src/unix.rs
Closes #182 
The signal handler may be called at any time in the thread, so it's not safe to use `RefCell`. Here we use a OS pipe to avoid any possible signal-unsafe functions. However, it needs another thread to notify the events.
> fix(signal,unix): use pipe

- azure-pipelines.yml
- compio-driver/Cargo.toml
- compio-driver/src/fusion/mod.rs
- compio-driver/src/iour/mod.rs
Use `squeue::Entry128` and `cqueue::Entry32` behind the feature gate. It could be enabled on Ubuntu 22.04 but not Ubuntu 20.04
Closes #191 
And thanks advice and requests from @oxalica
> feat(driver,iour): add large sqe & cqe support

- compio-runtime/src/attacher.rs
All IO resources should be !Send and !Sync, unless they are wrapped by Unattached.
> fix(runtime): attacher should be !Send & !Sync

- compio-io/Cargo.toml
- compio-io/src/lib.rs
- compio-io/src/split.rs
- compio-io/tests/io.rs
- compio-net/src/lib.rs
- compio-net/src/split.rs
- compio-net/src/tcp.rs
- compio-net/src/unix.rs
- compio-net/tests/split.rs
> feat(io,net): add split

- .github/workflows/ci_check.yml
- azure-pipelines.yml
> ci: Migrate check workflow to GHA

- compio-tls/Cargo.toml
Rustls starts to use aws-lc-rs as default provider, which means there are at least 2 working providers. We as the lib author should not force the users to use any of them. Thus the default feature of rustls is disabled.
> feat(dep): upgrade rustls to 0.23

- compio-net/src/unix.rs
- compio-net/tests/split.rs
- compio-net/tests/unix_stream.rs
- compio/examples/unix.rs
Previously we failed because, on Windows, ConnectEx requires a bound socket. We can bind it to an empty address.
> feat(net): async connect unix stream

- compio-driver/src/iocp/mod.rs
- compio-fs/Cargo.toml
- compio-fs/src/lib.rs
- compio-fs/src/stdio/mod.rs
- compio-fs/src/stdio/unix.rs
- compio-fs/src/stdio/windows.rs
- compio/Cargo.toml
Closes #207 
I put them under compio-fs. No good reasons, but seems clearer.
> feat: add stdio

- compio-buf/src/io_buf.rs
- compio-buf/src/iter.rs
- compio-buf/src/slice.rs
- compio-io/src/buffer.rs
- compio/tests/runtime.rs
> fix(buf): make IoBuf(Mut) unsafe

- compio-driver/src/iocp/mod.rs
- compio-driver/src/iocp/op.rs
- compio-fs/src/stdio/windows.rs
- compio-runtime/tests/event.rs
This PR adds Win32 event support for IOCP driver. Win32 event is kind of foundamental syncronize object. It could be, e.g., an event handle, an input console handle, a pipe handle, or a mutex handle.
Win32 event could not be polled by IOCP, but IOCP could be waited as a usual event on Windows 10+. `MsgWaitForMultipleObjectsEx` is used here to wait them all, and reserves possibility for APC routines and window messages. If there are more than 62 events to be waited, the remain events will be waited in seperate threads.
In this PR, stdio is also refactored to use the new feature. To make the code simpler, the console code page is forced to UTF8.
This PR is a prediction of the planned `compio-process`. We need the feature to wait for the process handle.
> feat(driver,windows): add win32 event support

- flake.lock
- flake.nix
This PR adds [flake.nix](https://nixos.wiki/wiki/Flakes), which contains a devShell config that can be used by `nix develop` to configure proper develop environment.
> build: add flake.nix

- compio-driver/src/iour/mod.rs
I'm not sure if the change is wise. It removes the outer squeue, and the operations will report errors when the squeue is full. It might be an optimization, but may produce errors to the user in the case that only stucks the runtime previously.
> fix(driver,iour): remove outer squeue

- compio-driver/src/poll/op.rs
- compio-driver/tests/file.rs
- compio-fs/src/open_options/unix.rs
- compio/examples/driver.rs
Kqueue always signals ready for regular files. We should use thread pool for them.
> fix(driver,poll): use blocking file io

- compio-driver/src/iour/op.rs
- compio-driver/src/unix/op.rs
- compio-driver/tests/file.rs
The libc crate does not provide statx on musl, and msghdr contains private padding fields :(
See also: https://github.com/DataDog/glommio/pull/590
---
Interestingly I'm getting one test failure on my machine:
```
---- cancel_before_poll stdout ----
thread 'cancel_before_poll' panicked at compio-driver/tests/file.rs:72:24:
index out of bounds: the len is 0 but the index is 0
```
> fix(unix,iour): musl libc compatibility

- compio-driver/src/poll/op.rs
- compio-driver/src/unix/op.rs
`statx` should only be used for *-linux-gnu targets.
> fix(driver): use statx only on linux-gnu

- compio-io/Cargo.toml
- compio-io/src/buffer.rs
- compio-io/src/compat.rs
- compio-io/tests/compat.rs
The type `AsyncStream` is exacted from cyper-core. It provides a stream with futures io impls to provide convenience.
> feat(io): compat async stream for futures

- compio-runtime/src/runtime/time.rs
Currently the faulty implementation of `min_timeout` yields the greatest delay of current entries, which could cause misbehavior when multiple timers are used. For example:
```rust
#[compio::main]
async fn main() -> Result<()> {
compio::runtime::spawn(async move {
compio::time::sleep(std::time::Duration::from_secs(1)).await;
println!("1s elapsed");
})
.detach();
compio::time::sleep(Duration::from_secs(5)).await;
println!("5s elapsed");
Ok(())
}
```
This will hang for 5 seconds and prints two statements without specific order.
Simply reversing the order of `TimeEntry` fixes the problem. Also a unit test is added.
> fix(runtime): incorrect min_timeout

- compio-driver/src/fd.rs
- compio-driver/src/fusion/op.rs
- compio-driver/src/iocp/mod.rs
- compio-driver/src/iocp/op.rs
- compio-driver/src/iour/op.rs
- compio-driver/src/lib.rs
- compio-driver/src/op.rs
- compio-driver/src/poll/op.rs
- compio-driver/src/unix/op.rs
- compio-fs/src/file.rs
- compio-fs/src/named_pipe.rs
- compio-fs/src/pipe.rs
- compio-fs/src/stdio/windows.rs
- compio-net/src/socket.rs
- compio-net/src/tcp.rs
- compio-net/src/udp.rs
- compio-net/src/unix.rs
- compio-runtime/src/attacher.rs
A SharedFd is generic to hold the original handle type. An OwnedFd is type-erased to support close operations. This PR is the basis of #224 , and will be convenient for AsyncFd in the future.
> refactor(driver): generic SharedFd

- compio-driver/src/lib.rs
- compio-fs/src/async_fd.rs
- compio-fs/src/lib.rs
- compio-fs/src/named_pipe.rs
- compio-fs/src/stdio/unix.rs
It is especially important to use AsyncFd in stdio on Unix, because the old implementation uses ManuallyDrop, which is a potential leak because Sender and Receiver started to use SharedFd inside after #230 .
NamedPipeServer is also changed to use AsyncFd only to check if there are possible bugs on Windows.
> feat(fs): AsyncFd

- compio-runtime/Cargo.toml
- compio-runtime/src/runtime/mod.rs
- compio-runtime/src/runtime/time.rs
- compio-runtime/tests/custom_loop.rs
Each call to `Waker::wake` writes to the eventfd, which is too annoying. This PR provides a faster path. When the waker is on the same thread, no need to write to the eventfd.
The `enable_poll` switch of proactor builder provides compatibility to custom event loops, which may poll the io-uring fd in other frameworks. When the switch is enabled, the fast path is disabled.
> feat(driver): reduce eventfd IO

- compio-driver/Cargo.toml
- compio-driver/src/fd.rs
- compio-driver/src/fusion/mod.rs
- compio-driver/src/iocp/cp/global.rs
- compio-driver/src/iocp/cp/mod.rs
- compio-driver/src/iocp/cp/multi.rs
- compio-driver/src/iocp/mod.rs
- compio-driver/src/iour/mod.rs
- compio-driver/src/key.rs
- compio-driver/src/lib.rs
- compio-driver/src/poll/mod.rs
- compio-driver/src/unix/mod.rs
- compio-driver/tests/file.rs
- compio-runtime/src/runtime/mod.rs
- compio-runtime/src/runtime/op.rs
- compio-runtime/src/runtime/time.rs
- compio/examples/driver.rs
In this way, no need the `OpRuntime`, and the HashMap could be removed.
> feat(driver): move future state into RawOp

- compio-buf/src/io_buf.rs
- compio-buf/src/lib.rs
- compio-dispatcher/src/lib.rs
- compio-driver/src/iour/mod.rs
- compio-fs/src/async_fd.rs
- compio-fs/src/file.rs
- compio-fs/src/metadata/unix.rs
- compio-fs/src/named_pipe.rs
- compio-fs/src/open_options/unix.rs
- compio-fs/src/pipe.rs
- compio-fs/src/stdio/windows.rs
- compio-fs/src/utils/unix.rs
- compio-io/src/read/ext.rs
- compio-io/src/read/mod.rs
- compio-io/src/write/mod.rs
- compio-net/src/socket.rs
- compio-runtime/Cargo.toml
- compio-runtime/src/attacher.rs
- compio-runtime/src/lib.rs
- compio-runtime/src/runtime/mod.rs
- compio-runtime/src/runtime/op.rs
- compio-runtime/src/runtime/time.rs
- compio-runtime/src/time.rs
- compio-runtime/tests/custom_loop.rs
- compio-runtime/tests/event.rs
- compio/benches/fs.rs
- compio/benches/monoio_wrap/mod.rs
- compio/benches/net.rs
* impl IoBuf for Rc & Arc
* check is_empty before pop when using SegQueue
* use `scoped-tls` instead of Weak tls
* The idea is from `monoio`, who copies code of `scoped-tls` into its own codebase. It reduces time when getting current `Runtime`.
I also found that the cost of `SendWrapper` is significant, but it will be addressed by #252 .
The benchmark shows that on Linux, compio is 15% (14% with LTO, and 5% with faster `SendWrapper`) *slower* than tokio; on Windows, compio is 5% (18% with LTO) *faster* than tokio.
> perf(net): rewrite net bench and optimize

- compio-dispatcher/Cargo.toml
- compio-dispatcher/src/lib.rs
- compio-dispatcher/tests/listener.rs
- compio-runtime/src/lib.rs
- compio-runtime/src/runtime/mod.rs
- compio/examples/dispatcher.rs
This PR reduces allocation in the process of dispatching, and adds ability to recover the closure passed in by the user.
> refactor(dispatcher): reduces alloc and API change

- compio-driver/src/iour/mod.rs
- compio-driver/src/lib.rs
- compio-signal/src/lib.rs
io-uring supports the `sqpoll` feature, which reduces syscalls during heavy IO operations.
However, infrequent IO operations may lead to excessive CPU utilization, so `sqpoll` is disabled by default
> feat(driver): add io-uring sqpoll support

- compio-dispatcher/src/lib.rs
- compio-driver/src/asyncify.rs
This PR adds `dispatch_blocking` to dispatcher that utilizes the asyncify pool.
In this PR:
- Asyncify pool now accepts dispatchables other than `FnOnce`
- Added `dispatch_blocking` that returns `Result<oneshot::Receiver<R>>` to obtain the result from the spawned task
> feat(dispatcher): dispatch blocking fn's

- Cargo.toml
- compio-driver/src/iocp/cp/mod.rs
- compio-driver/src/iocp/mod.rs
- compio-driver/src/iocp/op.rs
- compio-driver/src/iour/op.rs
- compio-driver/src/op.rs
- compio-driver/src/poll/mod.rs
- compio-driver/src/poll/op.rs
- compio-driver/src/unix/op.rs
- compio-fs/src/named_pipe.rs
- compio-process/Cargo.toml
- compio-process/src/lib.rs
- compio-process/src/linux.rs
- compio-process/src/unix.rs
- compio-process/src/windows.rs
- compio-process/tests/process.rs
- compio-runtime/src/attacher.rs
- compio/Cargo.toml
- compio/src/lib.rs
This PR adds a new crate, `compio-process`.
* Windows: driver is modified to accept APC routines. This is required for anonymous pipes to child process.
* Linux: tries to create a pidfd. If failed, fallback to `spawn_blocking`.
> feat(process): compio-process

- compio-runtime/Cargo.toml
- compio-runtime/src/runtime/mod.rs
- compio-runtime/src/runtime/send_wrapper.rs
> feat(runtime): faster SendWrapper with cached thread id

- compio-driver/src/poll/mod.rs
We have noticed that the CI on Linux sometimes reports an error on the dispatcher test, but haven't found the cause until now. The reason isn't related to the dispatcher, but because the epoll returns `ENOENT` if the fd is reused by another source while we still call `modify` to change the event. The solution is simple: remove the fd from the registry and poll if no op is waiting for it.
> fix(driver,poll): ENOENT on Linux

- Cargo.toml
- compio-driver/Cargo.toml
- compio-driver/src/iocp/cp/global.rs
- compio-driver/src/iocp/cp/mod.rs
The ArrayVec here is too large to copy. Use Vec instead.
> fix(driver,iocp): use Vec instead of ArrayVec

- compio-driver/src/iour/mod.rs
- compio-driver/src/key.rs
- compio-driver/src/lib.rs
- compio-driver/tests/file.rs
- compio-runtime/src/lib.rs
- compio-runtime/src/runtime/mod.rs
- compio-runtime/src/runtime/op.rs
- compio/examples/driver.rs
this PR allow compio driver and runtime not only return the IO result, but also return the flags
> feat: add flags related methods

- compio-driver/src/iocp/op.rs
- compio-driver/src/iour/op.rs
- compio-driver/src/op.rs
- compio-driver/src/poll/op.rs
- compio-driver/src/unix/op.rs
- compio-net/src/cmsg/mod.rs
- compio-net/src/cmsg/unix.rs
- compio-net/src/cmsg/windows.rs
- compio-net/src/lib.rs
- compio-net/src/socket.rs
- compio-net/src/udp.rs
- compio-net/tests/cmsg.rs
- compio-net/tests/udp.rs
This PR added support for control messages, or rather ancillary data.
- `compio-driver`: new opcode `RecvMsg` and `SendMsg`
- `compio-net`:
- Add `CMsgIter` and `CMsgBuilder` helper to deal with control message
- Add `recv_msg`, `send_msg` and vectored variant on `Socket`
- Add `set_socket_option` on `Socket`
- Add corresponding unit tests
> feat: add ancillary data support

- compio-fs/tests/file.rs
This PR will add a new test case for read with timeout.
> test(fs): Add a test case for read with timeout

- compio-driver/src/iocp/op.rs
- compio-driver/src/op.rs
- compio-driver/src/unix/op.rs
- compio-net/src/socket.rs
- compio-net/src/udp.rs
- compio-net/tests/udp.rs
This PR fixes ancillary data support previously introduced in #275 by:
1. adapt to `IoVectoredBuf` changes made by #277 
2. respect control message length modified by syscall in `RecvMsg`
> fix(driver/net): ancillary data

- compio-driver/src/op.rs
- compio-io/src/compat.rs
Clippy added [`too_long_first_doc_paragraph`](https://rust-lang.github.io/rust-clippy/master/index.html#/too_long_first_doc_paragraph) rule recently. This PR fixes the warnings caused by this rule.
> doc: fix clippy "first doc comment paragraph is too long"

- compio-net/src/socket.rs
- compio-net/src/tcp.rs
- compio-net/src/unix.rs
Allow to create compio stream objects from std types
> Add from_std methods

- compio-signal/Cargo.toml
- compio-signal/src/lib.rs
- compio-signal/src/linux.rs
- compio/Cargo.toml
The implementation is simpler with signal fd. However, it sets the signal mask for only the current thread. On other platforms, it sets the handler for all processes. It is a potential inconsistency. What do you think? @George-Miao
> feat: use signalfd on Linux

- .github/workflows/ci_test.yml
The next step would be deciding an MSRV and we can mark it in Cargo.toml `rust-version` and guard it by CI.
> ci: guard compio is compatible with stable rust

- compio-fs/Cargo.toml
- compio-fs/src/metadata/unix.rs
The types of some integers should be fixed on armv7 Android.
> fix(fs): metadata types on armv7-linux-androideabi

- compio-tls/Cargo.toml
- compio-tls/src/stream/mod.rs
- compio-tls/src/stream/rtls.rs
This is essential for HTTP 2 support.
> feat(tls): add ALPN support

- compio-io/Cargo.toml
- compio-io/src/compat.rs
Useful for different `Read` and `AsyncRead` definitions.
> feat(io): add *_read_uninit for compat

- compio-runtime/Cargo.toml
- compio-runtime/src/runtime/mod.rs
- compio-runtime/tests/custom_loop.rs
We should allow the futures self wake.
> feat(runtime): don't try to poll all tasks before polling driver

- compio-io/Cargo.toml
- compio-io/tests/compat.rs
- compio-io/tests/io.rs
- compio-net/Cargo.toml
- compio-net/src/udp.rs
`cyper` will use it to create a dual-stack endpoint.
> feat(net): add from_std for UdpSocket

- compio-driver/Cargo.toml
- compio-driver/src/iour/mod.rs
- compio-driver/src/poll/mod.rs
- compio-net/src/cmsg/mod.rs
- compio-net/src/cmsg/unix.rs
- compio-net/src/cmsg/windows.rs
- compio-tls/tests/connect.rs
Closes #305 
Some other changes are made to make clippy happy.
> fix(driver,poll,iour): use Arc::clone instead of try_clone

- compio-driver/Cargo.toml
- compio-driver/src/poll/mod.rs
- compio-runtime/Cargo.toml
`polling::Poller` itself contains a notify method. We didn't use it previously because at that time the poller is not in `Arc`.
> fix(driver,poll): remove pipe usage

- compio-quic/src/connection.rs
> fix(quic): don't exit event loop on I/O error

- compio-driver/src/iour/mod.rs
- compio-driver/src/iour/op.rs
- compio-driver/src/key.rs
- compio-driver/src/poll/op.rs
- compio-driver/src/unix/op.rs
- compio-net/src/socket.rs
On Unix, the accept operation may be cancelled after completed. In that case the accepted fd is leaked and the client may stuck. This PR fixes the issue by temporarily storing the fd in the op.
The issue doesn't affect IOCP.
> fix(net,iour,poll): fix accept leak

- compio-driver/src/lib.rs
- compio-driver/src/poll/op.rs
Make `syscall` retry calling when the syscall returns `EINTR`. We just assume `io-uring` won't return that.
> fix(driver,poll): ignore EINTR and retry

- compio-driver/src/iocp/mod.rs
- compio-net/Cargo.toml
- compio-net/src/lib.rs
- compio-net/src/resolve/windows.rs
- compio/Cargo.toml
Only in async resolve is `WSAStartup` needed. In other cases, `socket2` helps us.
This change will benefit the users who don't use sockets at all. They won't need to load WS2_32.dll at startup.
> refactor(net,iocp): move WSAStartup

- compio-driver/src/fusion/op.rs
- compio-driver/src/poll/mod.rs
- compio-driver/src/poll/op.rs
This is the first part of #310 . `event: Event` is a useless param in `on_event` now.
> refactor(driver,poll): remove event in on_event

- compio-driver/src/fusion/mod.rs
- compio-driver/src/fusion/op.rs
- compio-driver/src/poll/mod.rs
- compio-driver/src/poll/op.rs
This is the second part of #310 . It adds `OpType` to operation to determine whether it is a poll operation or AIO operation (not in this PR). It is a workaround because `polling` doesn't expose APIs to get a kqueue AIO event.
> refactor(driver,poll): add op_type

- .github/workflows/ci_test_freebsd.yml
- .github/workflows/ci_test_illumos.yml
- compio-quic/Cargo.toml
- compio-quic/benches/quic.rs
- compio-quic/src/socket.rs
- compio-quic/tests/echo.rs
Trying to add illumos CI based on omnios CI. If succeeds, I'll enable AIO on illumos and solaris.
> ci: add illumos one

- Cargo.toml
- compio-dispatcher/Cargo.toml
- compio-driver/Cargo.toml
- compio-fs/Cargo.toml
- compio-io/Cargo.toml
- compio-net/Cargo.toml
- compio-process/Cargo.toml
- compio-quic/Cargo.toml
- compio-runtime/Cargo.toml
- compio-signal/Cargo.toml
- compio-tls/Cargo.toml
- compio/Cargo.toml
Note: I don't prepare to update `compio-buf` because it was only re-formatted from 0.12 to now.
> feat: prepare for 0.13 release

- compio-runtime/src/runtime/mod.rs
- compio-runtime/src/runtime/op.rs
Original `OpFuture` was renamed to `OpFlagsFuture` in #272 for addition of flag. But I think the rename is unnecessary and `OpFlagsFuture` looks tedious, so I'd like to rename it back. Besides it's not a public API so such renaming will not be a breaking change.
> refactor(runtime): Rename `OpFlagsFuture` back to `OpFuture`

- compio-driver/src/fusion/mod.rs
- compio-driver/src/iocp/mod.rs
- compio-driver/src/iocp/wait/packet.rs
- compio-driver/src/iocp/wait/thread_pool.rs
- compio-driver/src/iour/mod.rs
- compio-driver/src/lib.rs
- compio-driver/src/poll/mod.rs
It would benefit the binary size, but I don't know if it would benefit the performance.
> fix(driver): erase op type in driver

- compio-runtime/Cargo.toml
- compio-runtime/src/runtime/mod.rs
- compio-runtime/src/runtime/op.rs
- compio-runtime/src/runtime/time.rs
Closes #349 
I have to revert the changes of Arc -> Box. To avoid ref cycle, the runnables are popped manually on drop.
`self.enter` is used to make sure `OpFuture` and `TimerFuture` find the correct current runtime on drop.
> fix(runtime): drop runnables manually

- compio/Cargo.toml
It makes users cannot remove rustls easily.
> fix: remove "ring" from default features

- compio-runtime/Cargo.toml
- compio-runtime/src/runtime/mod.rs
> fix(runtime): fix runtime drop borrowing

- compio-fs/src/pipe.rs
- compio-net/src/socket.rs
- compio-signal/src/linux.rs
If fusion driver enabled, we can only check the driver type on runtime.
> fix(fs,net,signal): check driver type on runtime

- compio-runtime/src/runtime/mod.rs
The drivers has been fixed by #308 , so we don't need to loop in the runtime.
> fix(runtime): simplify spawn_blocking

- compio-fs/tests/file.rs
- compio-io/src/read/ext.rs
- compio-io/src/read/mod.rs
- compio-io/src/write/ext.rs
- compio-io/src/write/mod.rs
- compio-io/tests/io.rs
This is a refactor of vectored methods.
* Don't loop in fallback methods.
* More vectored methods for slices and vectors.
> refactor(io): revise vectored methods

- compio-driver/src/fusion/mod.rs
- compio-driver/src/iocp/mod.rs
- compio-driver/src/iour/mod.rs
- compio-driver/src/lib.rs
- compio-driver/src/poll/mod.rs
- compio-driver/tests/file.rs
- compio-runtime/src/runtime/mod.rs
I'm not sure whether we will change the implementation in the future, but it doesn't need to return `Result` now.
> refactor(driver): remove one Result usage

- compio-dispatcher/Cargo.toml
- compio-dispatcher/src/lib.rs
We can just use oneshot channel here.
> fix(dispatcher): replace event with oneshot channel

- compio-io/src/read/managed.rs
- compio-io/src/read/mod.rs
Split from #276, and renamed the names.
> feat(io): buffer pool IO traits

- compio-quic/Cargo.toml
- compio-quic/benches/quic.rs
Quinn added illumos support since [quinn-udp-0.5.8](https://github.com/quinn-rs/quinn/releases/tag/quinn-udp-0.5.8).
> chore(quic): re-enable quinn on solarish

- compio-tls/src/stream/mod.rs
`slice.fill(MaybeUninit::new(0))` will be called every time `read_buf()` is invoked, even if the buffer has been initialized previously.
> fix(tls): duplicated buffer init

- compio-net/src/socket.rs
- compio-net/src/tcp.rs
Didn't test, but I happened to see address in use errors when developing my app.
> fix(net): set reuseaddr when binding

- compio-net/src/tcp.rs
Docstrings are copied from std, is it ok?
> feat(net): TcpStream.nodelay, TcpStream.set_nodelay

- compio-buf/src/buf_result.rs
- compio-tls/src/stream/mod.rs
Print the caller that calls `BufResult::unwrap()`(also, `expect()`) instead of printing `BufResult` itself.
``` rust
use std::io;
use compio::BufResult;
fn main() {
let err = io::Result::<u8>::Err(io::Error::last_os_error());
let result = BufResult(err, 0u8);
result.unwrap();
}
```
>Before
>thread 'main' panicked at ~/compio-buf/src/buf_result.rs:88:17
>
>After
> thread 'main' panicked at src/main.rs:8:12
Set to `Result::unwrap()` flavor.
> fix(buf): track caller unwrapping

- .github/workflows/ci_test.yml
- compio-driver/Cargo.toml
- compio-driver/build.rs
- compio-driver/src/buffer_pool/fallback.rs
- compio-driver/src/buffer_pool/fusion.rs
- compio-driver/src/buffer_pool/iour.rs
- compio-driver/src/buffer_pool/mod.rs
- compio-driver/src/driver_type.rs
- compio-driver/src/fusion/mod.rs
- compio-driver/src/fusion/op.rs
- compio-driver/src/iocp/mod.rs
- compio-driver/src/iocp/op.rs
- compio-driver/src/iour/mod.rs
- compio-driver/src/iour/op.rs
- compio-driver/src/lib.rs
- compio-driver/src/op.rs
- compio-driver/src/poll/mod.rs
- compio-driver/src/poll/op.rs
- compio-driver/tests/file.rs
This PR is splited from #276 , with some changes.
/cc: @Sherlock-Holo 
Don't forget to add `Co-authored-by` when merging.
> feat(driver): buffer pool

- compio-quic/Cargo.toml
- compio-quic/src/recv_stream.rs
- compio-quic/src/send_stream.rs
We were previously using some `#[doc(hidden)] pub` of `quinn-proto`. In their latest release [0.11.10](https://github.com/quinn-rs/quinn/releases/tag/quinn-proto-0.11.10) they introduced some breaking changes about this.
See:
- https://github.com/quinn-rs/quinn/pull/2103
- https://github.com/quinn-rs/quinn/issues/2175
- https://github.com/hyperium/h3/pull/290
> fix(quic): usages of `#[doc(hidden)] pub`

- compio-driver/src/iour/mod.rs
- compio-driver/src/lib.rs
this can optimize performance for most cases
> perf(driver): set setup_coop_taskrun for io-uring

- compio-driver/src/iour/op.rs
- compio-driver/src/poll/op.rs
- compio-net/src/socket.rs
> Add `CLOEXEC` flags

- compio-quic/Cargo.toml
- compio-quic/examples/http3-client.rs
- compio-quic/examples/http3-server.rs
- compio-quic/src/connection.rs
- compio-quic/src/recv_stream.rs
- compio-quic/src/send_stream.rs
They changed a lot in this release.
Resolve #405 
Resolve #404
> feat(quic): update h3 to 0.0.8, h3-datagram to 0.0.2

- flake.nix
go and cmake is required to build `aws-lc-fips-sys` (used by compio-quic)
> build: add required dependencies to flake.nix

- compio-quic/Cargo.toml
`compio-quic` released on [crates.io](https://crates.io/crates/compio-quic) (and also `compio` it self with `quic` feature) does not work with fresh `Cargo.lock` due to semver-incompatible changes introduced in `quinn-proto` (see #389). A patch release should fix this issue.
> build: bump patch version for compio-quic

- compio-quic/benches/quic.rs
- Reuse endpoints (fix #393)
- Remove unnecessary parameters
- Improve concurrency
- Cross test with quinn as server or client
Example result (Linux, io_uring):
```
quic-echo/compio-quic/compio-quic
time:   [2.4146 ms 2.4912 ms 2.5750 ms]
thrpt:  [776.70 MiB/s 802.83 MiB/s 828.29 MiB/s]
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) high mild
Benchmarking quic-echo/quinn/compio-quic: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 8.6s, enable flat sampling, or reduce sample count to 50.
quic-echo/quinn/compio-quic
time:   [1.4626 ms 1.4850 ms 1.5125 ms]
thrpt:  [1.2914 GiB/s 1.3153 GiB/s 1.3354 GiB/s]
Found 10 outliers among 100 measurements (10.00%)
1 (1.00%) high mild
9 (9.00%) high severe …
```
> chore: rewrite compio-quic bench

- compio-driver/src/iour/mod.rs
- compio-driver/src/lib.rs
It's useful when users want to poll the driver themselves. Currently the only way is to call `libc::syscall`.
> feat(iour): allow register eventfd in Driver::new

- compio-dispatcher/Cargo.toml
- compio-fs/Cargo.toml
- compio-fs/src/pipe.rs
- compio-net/Cargo.toml
- compio-process/Cargo.toml
- compio-quic/Cargo.toml
- compio-runtime/Cargo.toml
- compio-signal/Cargo.toml
- compio-signal/src/linux.rs
- compio/Cargo.toml
I don't remember why we added so many useless features to these subcrates. Anyway we can determine the driver type on run time, and hope that rustc will optimize them.
> refactor: cleanup features

- compio-net/src/opts.rs
Rename the `TCP_NODELAY` flag to idiomatic version that follows the TCP standard.
> feat(net): rename tcp nodelay to idiomatic version

- compio-runtime/src/time.rs
cc @Berrysoft @George-Miao Is this reasonable?
> refactor: Avoid instantiating Elapsed outside
