Cargo.toml, examples/basic.rs, examples/driver.rs, src/driver/iocp/mod.rs, src/driver/iour/mod.rs, src/driver/mod.rs, src/lib.rs, src/task/runtime.rs, tests/driver.rs, tests/file.rs
=> Add more tests & fix.

Cargo.toml, src/driver/iocp/op.rs, src/net/mod.rs, src/net/udp.rs, src/net/unix.rs, tests/tcp_accept.rs, tests/udp.rs
=> Add some test port from monoio.

examples/driver.rs, src/driver/iocp/mod.rs, src/driver/iour/mod.rs, src/driver/mod.rs, src/task/runtime.rs
=> Change poll to batched operation.

src/task/op.rs, src/task/runtime.rs, src/task/time.rs
Slab will reuse the removed key. We need to combine all resources together in the slab.
=> Fix Slab usage.

azure-pipelines.yml
=> Add more jobs to pipeline.

src/driver/iocp/op.rs, src/driver/iour/op.rs, src/fs/file.rs, src/op.rs, tests/file.rs
It is sync (but lazy) method on Windows. Hope it won't cause much troubles...
=> Impl `sync_all` & `sync_data`.

benches/fs.rs, benches/named_pipe.rs, benches/net.rs, examples/basic.rs, examples/named_pipe.rs, examples/net.rs, examples/unix.rs, src/driver/iocp/fs.rs, src/driver/iocp/mod.rs, src/driver/iocp/op.rs, src/driver/iour/fs.rs, src/driver/iour/op.rs, src/fs/file.rs, src/named_pipe.rs, src/net/mod.rs, src/net/socket.rs, src/net/tcp.rs, src/net/udp.rs, src/net/unix.rs, tests/file.rs, tests/tcp_connect.rs, tests/unix_stream.rs
=> Add IO extension methods.

benches/driver.rs, src/driver/iocp/mod.rs, src/driver/iocp/op.rs, src/driver/iour/mod.rs, src/driver/mod.rs, src/driver/queue.rs, src/fs/file.rs, src/net/socket.rs
=> Fix warnings

src/driver/iocp/mod.rs, src/driver/mod.rs, src/event/iocp.rs, src/event/iour.rs, src/lib.rs, src/net/tcp.rs, src/net/udp.rs, src/net/unix.rs, src/task/mod.rs
=> Fix warnings.

Cargo.toml
* This change fix the cargo test error with default feature
=> Add extra configure target for event tests (#45)

Cargo.toml, README.md, examples/driver.rs, src/driver/iocp/mod.rs, src/driver/iour/mod.rs, src/driver/mio/mod.rs, src/driver/mod.rs, src/task/runtime.rs, tests/driver.rs
=> Batched submission & polling

README.md, examples/driver.rs, src/driver/iocp/mod.rs, src/driver/iour/mod.rs, src/driver/mio/mod.rs, src/driver/mod.rs, src/task/op.rs, src/task/runtime.rs
After #44 I realized that the submission queue could also be removed if we just submit at poll.
=> Move submission queue to runtime

src/driver/iocp/mod.rs, src/driver/iour/mod.rs, src/driver/mio/mod.rs, src/driver/mio/op.rs, src/driver/mod.rs, tests/driver.rs
=> Fix cancellation.

Cargo.toml, src/buf/io_buf.rs, src/lib.rs
=> Add allocator_api support.

Cargo.toml, README.md, src/buf/io_buf.rs, src/event/eventfd.rs, src/event/pipe.rs
Is it sound? I'm not sure.
/cc @George-Miao
=> Use read_buf feature if possible.

src/driver/iocp/mod.rs, src/driver/iour/mod.rs, src/driver/mio/mod.rs, src/driver/mod.rs, src/driver/unix/mod.rs, src/event/iocp.rs
It could be merged with the allocation of `RawOp`.
=> Reduce overlapped alloc

src/driver/iocp/mod.rs, src/driver/iocp/op.rs, src/driver/iour/mod.rs, src/driver/mio/mod.rs, src/driver/mod.rs, src/event/iocp.rs, tests/driver.rs
For future async cancellation use.
=> Make cancelled op return

Cargo.toml, azure-pipelines.yml, compio-buf/src/io_buf.rs, compio-buf/src/slice.rs, compio/Cargo.toml, compio/examples/driver.rs, compio/src/driver/mod.rs, compio/src/named_pipe.rs, compio/tests/driver.rs
=> fix: use `arrayvec` from `compio-buf`

Cargo.toml, compio-dispatcher/Cargo.toml, compio-dispatcher/src/lib.rs, compio-driver/src/iour/mod.rs, compio-fs/src/file.rs, compio-fs/src/named_pipe.rs, compio-net/src/socket.rs, compio-net/src/tcp.rs, compio-net/src/udp.rs, compio-net/src/unix.rs, compio-runtime/src/attacher.rs, compio-runtime/src/lib.rs, compio/Cargo.toml, compio/examples/dispatcher.rs, compio/src/lib.rs, compio/tests/dispatcher.rs, compio/tests/driver.rs, compio/tests/runtime.rs
Blocker: #85 
The example & test is alike. Do you have some advice? /cc @George-Miao @bdbai
=> Add a multi-threading dispatcher

compio-driver/src/iour/mod.rs
We can just create the submission entry earlier.
=> Remove cancel queue for io-uring driver.

compio-runtime/src/runtime/mod.rs
However, simply calling `wake` in other threads may not trigger reschedule. Therefore I don't know how to construct a panic test.
Closes #108 . According to the votes of the maintainers, we don't want to support futures channel working cross thread.
=> Make schedule Send with panics.

compio-net/Cargo.toml, compio-net/src/lib.rs, compio-net/src/resolve/glibc.rs, compio-net/src/resolve/mod.rs, compio-net/src/resolve/unix.rs, compio-net/src/resolve/windows.rs, compio-net/src/tcp.rs, compio-net/src/udp.rs
Just spawn a thread and wait it.
=> Make DNS resolve async on Unix

compio/examples/resolve.rs
Add an example of DNS resolve. Only to show the functionality.
=> docs(net): add example for async resolve.

Cargo.toml, compio-buf/Cargo.toml, compio-dispatcher/Cargo.toml, compio-driver/Cargo.toml, compio-fs/Cargo.toml, compio-io/Cargo.toml, compio-log/Cargo.toml, compio-macros/Cargo.toml, compio-net/Cargo.toml, compio-runtime/Cargo.toml, compio-signal/Cargo.toml, compio/Cargo.toml
`tls` and `http-*` won't be published.
=> fix: update version and prepare for beta release

README.md
=> fix: badges on README and versions

README.md
This PR adds a telegram badge to `README.md`.
=> doc: add telegram badge to README.md

compio-tls/Cargo.toml, compio-tls/src/adapter/rtls.rs, compio-tls/tests/connect.rs
=> feat(tls): update rustls to 0.22

compio-driver/Cargo.toml, compio-fs/Cargo.toml, compio-io/Cargo.toml, compio-net/Cargo.toml, compio-runtime/Cargo.toml, compio-signal/Cargo.toml, compio-tls/Cargo.toml, compio/Cargo.toml
Update versions and fix targets for docrs.
=> feat: prepare for 0.9.0-beta.4

compio-io/src/lib.rs, compio-io/src/read/mod.rs, compio-io/tests/io.rs
=> fix(io): remove incorrect AsyncRead impls

compio-driver/src/poll/mod.rs
Epoll may return event when there are no interest... but kqueue doesn't. I don't know if there are bugs in our code. Anyway, don't panic here.
=> fix(driver,poll): allow event with no interest

compio-signal/src/unix.rs
@George-Miao and I agreed to apply this change, but we forgot.
=> doc(signal): about spawning a thread for signal handler

compio-buf/src/io_buf.rs, compio-io/src/read/ext.rs, compio-io/src/write/ext.rs, compio-io/tests/io.rs
* Handle interrupt error
* Fix read length of read_exact: Closes #203
=> fix(io): read_exact and write_all

compio-io/src/buffer.rs, compio-io/src/compat.rs, compio-io/src/util/mod.rs, compio-io/src/write/buf.rs
=> fix(io): make buffer flush error safe

compio-driver/src/iocp/op.rs, compio-fs/src/open_options/windows.rs, compio-fs/tests/file.rs
Following a rust 1.76 std fix.
https://github.com/rust-lang/rust/pull/116438
=> fix(fs,windows): allow `File::create` on hidden files

compio-driver/Cargo.toml, compio-driver/src/iour/mod.rs, compio-driver/src/poll/mod.rs, compio-runtime/Cargo.toml, compio-runtime/src/runtime/mod.rs, compio-runtime/tests/custom_loop.rs
Two tests added to show how this hook could be used.
=> feat(runtime): a runtime hook API design

Cargo.toml, README.md, compio-buf/Cargo.toml, compio-dispatcher/Cargo.toml, compio-driver/Cargo.toml, compio-fs/Cargo.toml, compio-fs/src/stdio/unix.rs, compio-fs/src/stdio/windows.rs, compio-io/Cargo.toml, compio-log/Cargo.toml, compio-macros/Cargo.toml, compio-net/Cargo.toml, compio-runtime/Cargo.toml, compio-signal/Cargo.toml, compio-tls/Cargo.toml, compio/Cargo.toml
=> feat: prepare for 0.9.0 release

compio-runtime/src/runtime/mod.rs
I think it's not a breaking change.
=> refactor(runtime): return Task in spawn_blocking

compio/Cargo.toml, compio/benches/fs.rs
Any advice on the new benchmark code? @Xuanwo
=> refactor(bench): rewrite fs bench

compio-driver/src/iour/op.rs, compio-fs/tests/file.rs
=> fix(driver,iour): wrong impl of WriteVectoredAt

.github/workflows/ci_test.yml, compio-driver/Cargo.toml, compio-driver/src/fusion/mod.rs, compio-driver/src/iour/op.rs, compio-driver/src/op.rs, compio-driver/src/poll/op.rs, compio-driver/src/unix/op.rs, compio-net/src/socket.rs, compio-net/src/tcp.rs, compio-net/src/udp.rs, compio-net/src/unix.rs, compio-net/tests/split.rs, compio-net/tests/unix_stream.rs, compio/examples/unix.rs
The creation of socket is async now.
=> feat(driver): add CreateSocket

.gitignore, Cargo.toml, compio-dispatcher/Cargo.toml, compio-dispatcher/src/lib.rs, compio-dispatcher/tests/listener.rs, compio/examples/dispatcher.rs
This PR adds concurrency option to dispatcher
=> feat(dispatcher): Make concurrency

compio-fs/src/file.rs, compio-fs/src/metadata/unix.rs, compio-fs/src/metadata/windows.rs, compio-fs/src/open_options/windows.rs, compio-fs/src/utils/windows.rs, compio-net/src/resolve/unix.rs, compio-net/src/socket.rs, compio-net/tests/split.rs, compio-net/tests/tcp_accept.rs, compio-net/tests/tcp_connect.rs, compio-runtime/src/runtime/mod.rs, compio-runtime/tests/event.rs, compio/tests/runtime.rs
It is needed for dispatcher to perform stably.
=> feat(runtime): catch unwind in spawn*

.github/workflows/ci_check.yml, compio-driver/src/fusion/mod.rs, compio-fs/Cargo.toml, compio-net/Cargo.toml, compio/Cargo.toml
Finally, rustc & clippy checks if the specified feature doesn't exist.
=> fix: feature typo

compio-net/src/tcp.rs
=> test(net): use random port

compio-macros/src/main_fn.rs
this should allow it to run on other functions
=> refactor(macro): remove compio::main restrictions

Cargo.toml, compio-buf/Cargo.toml, compio-dispatcher/Cargo.toml, compio-driver/Cargo.toml, compio-fs/Cargo.toml, compio-io/Cargo.toml, compio-macros/Cargo.toml, compio-net/Cargo.toml, compio-runtime/Cargo.toml, compio-signal/Cargo.toml, compio/Cargo.toml
I'll publish it after approved, and I'll merge this PR manually after it is published successfully.
=> feat: prepare for 0.11.0 release

compio-buf/src/buf_result.rs
=> fix(buf): remove unreachable pattern

.github/workflows/ci_test.yml, compio-quic/Cargo.toml, compio-quic/src/builder.rs
=> build(deps): update rustls platform verifier

.github/workflows/ci_test_freebsd.yml, compio-quic/tests/echo.rs
This is the third part of #310 .
=> ci: add freebsd

compio-driver/src/fusion/mod.rs, compio-driver/src/op.rs, compio-driver/src/poll/mod.rs, compio-driver/src/poll/op.rs, compio-driver/src/unix/op.rs
I'm trying to add a FreeBSD CI. Then we can test AIO on it.
=> feat: add FreeBSD AIO support

compio-runtime/src/runtime/mod.rs
The schedule closure keeps strong ref to the runnable collections, while the closure is owned by the runnable. It is a reference cycle. This PR turns the strong ref to weak ref.
=> fix(runtime): runnable reference cycle

compio-runtime/src/runtime/mod.rs
It should be safe to make a self-reference with Box. The runnable queue is moved prior to the proactor, because the schedule closure should outlive the wakers.
=> fix(runtime): self-reference without Arc

compio-driver/Cargo.toml, compio-driver/src/fusion/mod.rs, compio-driver/src/iocp/mod.rs, compio-driver/src/iour/mod.rs, compio-driver/src/lib.rs, compio-driver/src/poll/mod.rs, compio-driver/tests/file.rs, compio-runtime/Cargo.toml, compio-runtime/src/runtime/mod.rs, compio/examples/driver.rs, compio/tests/runtime.rs
Need to consider a test for that...
=> refactor(driver,runtime): allow polling driver when pushing an op

.github/workflows/ci_check.yml, compio-quic/Cargo.toml, compio-quic/build.rs, compio-quic/src/builder.rs, compio-quic/src/connection.rs, compio-quic/src/endpoint.rs, compio-quic/src/lib.rs
=> feat(quic): support rustls provider aws-lc-rs

.github/workflows/ci_test.yml, Cargo.toml, compio-tls/Cargo.toml, compio/Cargo.toml
`ring` is specified by default.
=> fix: add rustls features for tls

compio-driver/src/poll/mod.rs
=> fix(poll): cancel in the fd queue

compio-driver/src/iocp/cp/mod.rs, compio-driver/src/iocp/wait/packet.rs
https://github.com/rust-lang/rust/blob/master/library/std/src/sys/pal/windows/c.rs#L34-L38
=> fix(driver,iocp): check NTSTATUS correctly

compio-driver/src/iocp/op.rs, compio-driver/src/iour/op.rs, compio-driver/src/poll/op.rs, compio-runtime/src/runtime/mod.rs
This PR removes some limitations of `spawn_blocking`.
=> feat(runtime): relax signature of `spawn_blocking`

compio-io/Cargo.toml, compio-io/src/framed/frame.rs
=> feat(io): allow set length_field_len and length_field_is_big_endian for LengthDelimited

compio-driver/src/fd.rs, compio-driver/src/fusion/mod.rs, compio-driver/src/fusion/op.rs, compio-driver/src/iocp/mod.rs, compio-driver/src/iocp/op.rs, compio-driver/src/iour/mod.rs, compio-driver/src/iour/op.rs, compio-driver/src/lib.rs, compio-driver/src/op.rs, compio-driver/src/poll/mod.rs, compio-driver/src/poll/op.rs, compio-driver/src/unix/op.rs, compio-fs/src/async_fd.rs, compio-fs/src/stdio/unix.rs, compio-fs/src/stdio/windows.rs, compio-net/src/poll_fd/mod.rs, compio-net/src/poll_fd/unix.rs, compio-net/src/poll_fd/windows.rs, compio-process/src/lib.rs, compio-process/src/linux.rs, compio-process/src/unix.rs, compio-process/src/windows.rs, compio-runtime/src/attacher.rs
Closes #423 
Should we change all `AsRawFd` constraints in `compio-driver` to `AsFd`?
=> fix(driver): add `AsFd` requirements for `SharedFd`

compio-fs/src/file.rs, compio-fs/src/named_pipe.rs, compio-fs/tests/buffer_pool.rs, compio-io/src/read/managed.rs
Has been discussed in the tg group.
=> feat(io): adjust read_managed_at param order

Cargo.toml, compio-driver/Cargo.toml, compio-driver/src/fusion/mod.rs, compio-driver/src/iocp/cp/global.rs, compio-driver/src/iocp/cp/mod.rs, compio-driver/src/iocp/mod.rs, compio-driver/src/iocp/op.rs, compio-driver/src/iocp/wait/packet.rs, compio-driver/src/iocp/wait/thread_pool.rs, compio-driver/src/iour/mod.rs, compio-driver/src/iour/op.rs, compio-driver/src/lib.rs, compio-driver/src/op.rs, compio-driver/src/poll/mod.rs, compio-driver/src/poll/op.rs, compio-driver/src/unix/op.rs, compio-net/src/opts.rs, compio-net/src/resolve/windows.rs, compio-net/src/tcp.rs, compio-net/src/unix.rs, compio-quic/Cargo.toml, compio-quic/benches/quic.rs, compio-quic/examples/http3-server.rs, compio-quic/examples/quic-dispatcher.rs, compio-quic/examples/quic-server.rs, compio-quic/tests/common/mod.rs, compio-runtime/tests/custom_loop.rs, compio-runtime/tests/event.rs, compio-signal/src/windows.rs
=> feat: update socket2, windows-sys, rcgen

compio-driver/src/iour/mod.rs
It addresses a bug found in #460. I'm not sure if it's the root cause.
@inklesspen1rus Could you try this PR and watch if the problem in #460 still exists?
=> fix(driver,iour): resubmit poll op

compio-driver/src/fusion/op.rs, compio-driver/src/iour/mod.rs, compio-driver/src/iour/op.rs
Just some `cfg`s that we haven't remove. They are needless after bufring is not an optional feature.
=> refactor(driver): remove some cfg(io_uring)
